# Generated by Django 5.1.4 on 2025-05-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_sellerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='was_seller',
            field=models.BooleanField(default=False),
        ),
    ]
