# Generated by Django 5.1.4 on 2024-12-25 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_livestock_owner_alter_livestock_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestock',
            name='owner',
        ),
    ]
