# Generated by Django 5.1.4 on 2025-03-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_remove_livestock_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
